# transfer_trans is defined as (palm frame in hand base frame)
# palm frame is the sampled frame from object surface 
# (in BODex, it is defined as x towards object, y towards right hand's thumb)
# hand base frame is defined by the hand URDF

rh_palm:
  # r: [[0.0, -1, 0],[1, 0, 0],[0, 0, 1]]
  # t: [0.0, 0.0, -0.08]
  r: [[ 1.11022302e-16,  1.00000000e+00,  0.00000000e+00],
      [-8.66025404e-01,  1.11022302e-16,  5.00000000e-01],
      [ 5.00000000e-01, -1.11022302e-16,  8.66025404e-01]]
  t: [0.0, 0.0, 0.05]