world:
  type: scene_cfg
  template_path: object/DGN_2k/scene_cfg/**/floating/*.npy
  start:
  end: 


robot_file: "right_shadow_hand_sim.yml"
# robot_file_with_arm: "ur10e_shadow_sim.yml"
robot_file_with_arm:
base_cfg_file: "base_grasp.yml"
particle_file: "particle_grasp_debug.yml"
gradient_file: "gradient_grasp_fc.yml"

exp_name: 'debug'
seed_num: 20
seeder_cfg:
  obj_sample:
    num: 128
    inflate: 0.1
    convex_hull: True
    collision_free: True 
  ik_init_q:
  load_path: 
  skip_transfer: False
  t:  
  r:  
  q: [ 0, 1.2, 0, -0.2, 0, -0.1, 0.3, 0., 0., 0, 0.3, 0., 0., -0.1, 0.3, 0., 0., 0, -0.2, 0.3, 0., 0.] # qpose: TH, FF, MF, RF, LF
  jitter_angle: [[-180, -15, -15], [180, 15, 15]]
  jitter_dist: [[0.0, -0.03, -0.03], [0.03, 0.03, 0.03]]

grasp_contact_strategy:
  contact_points_name: ['rh_ffdistal/2', 'rh_mfdistal/2', 'rh_rfdistal/2', 'rh_lfdistal/2', 'rh_thdistal/1']
  contact_normals:
    [
        [0, -1, 0],
        [0, -1, 0],
        [0, -1, 0],
        [0, -1, 0],
        [0, -1, 0],
    ]
  opt_progress: [0.0, 0.6, 0.8]
  distance: [0.01, 0.01, 0.0]
  contact_query_mode: [-1, 0, 0]
  save_qpos: [False, True]
  pregrasp_stage: 1
  grasp_stage: 2
  max_ge_stage: 0

grasp_cfg:
  task_dict:
    f: [0, 0, 1]
    p: [0, 0, 0]
    t: [0, 0, 0]
    gamma: 180
  ge_param:
    type: 'qp'
    miu_coef: [0.1, 0]
    solver_type: 'batch_reluqp'
    k_lower: 0.2
    groups: [[0, 1, 2, 3, 4]]
    weights: [1.0]
    multi_ge_type: "concate"
    pressure_constraints:   # [contact_id_list, lower, upper]
      [[[0, 1, 2, 3, 4], 1.0, 5.0],
        [[0, 1, 2], 0.4, 3.0], 
        [[4], 0.5, 1.0], 
      ]
    enable_density: False
    solve_interval: 5

gradient: 
  cost:
    grasp_cfg: 
      weight: [
                [100, 1000, 100, 0],
                [100, 1000, 100, 0],
                [100, 1000, 100, 0],
              ] # grasp loss, dist loss, regu loss, normal loss for each contact stage
  lbfgs:
    n_iters: 500
    inner_iters: 50
    base_scale: [0.01, 0.1, 0.1]

mogen_init: [0.4227, -1.5991, -1.8872, -3.0432, -0.9848,  3.2433,  0.1738, -0.2078, 0,0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,0]